package com.example.framegate.domain.queue

import com.example.framegate.domain.model.Metrics
import kotlinx.serialization.Serializable

// PENDING -> UPLOADING -> COMPLETED; upon failure -> PENDING (retry) or FAILED.
enum class QueueItemStatus {
    PENDING,
    UPLOADING,
    COMPLETED,
    FAILED;

    val isTerminal: Boolean
        get() = this == COMPLETED || this == FAILED
}

/**
 * Queued capture record. [idempotencyKey] is generated by the client and remains
 * stable throughout the lifecycle of the record (even across app crashes), allowing
 * the server to deduplicate and ensure exactly-once upload semantics.
 */
@Serializable
data class QueueItem(
    val id: String,
    val idempotencyKey: String,
    val timestampEpochMillis: Long,
    val planName: String,
    val scaleFactorRaw: String,
    val orientation: Int,
    val roi: SerializableRoi,
    val metrics: SerializableMetrics,
    // File path of the capture artifact on disk; the record stores the path, not raw bytes.
    val artifactPath: String = "",
    val status: QueueItemStatus = QueueItemStatus.PENDING,
    val attempts: Int = 0,
    val lastError: String? = null,
)

/** Normalized ROI, serializable for the queue journal and upload manifest. */
@Serializable
data class SerializableRoi(
    val x: Float,
    val y: Float,
    val width: Float,
    val height: Float,
)

/** Serializable metrics for the queue journal and upload manifest. */
@Serializable
data class SerializableMetrics(
    val focus: Float,
    val meanLuma: Float,
    val clippedFraction: Float,
    val motion: Float,
) {
    companion object {
        fun from(metrics: Metrics): SerializableMetrics =
            SerializableMetrics(metrics.focus, metrics.meanLuma, metrics.clippedFraction, metrics.motion)
    }
}
